//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string BOAT_EVENT_IMPACT = "boat_event_impact";
        
        public const string BOAT_SWAY_HEAVY = "boat_sway_heavy";
        
        public const string BOAT_SWAY_LIGHT = "boat_sway_light";
    }
}
